language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
install: "pip install -r requirements.txt"

script:
  nosetests --with-coverage --cover-inclusive --cover-package=gglsbl3
after_success:
  coveralls
